<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>WGU_C969_Software_II_CS</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\CustomerFormLocal.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>CustomerForm.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\AddressFormLocal.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>AddressForm.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\CustomerFormLocal.es-es.resx">
        <DependentUpon>CustomerFormLocal.resx</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\AddressFormLocal.es-es.resx">
        <DependentUpon>AddressFormLocal.resx</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\CityFormLocal.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>CityFormLocal.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\AppointmentForm.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>AppointmentForm.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\AppointmentForm.es-es.resx">
        <DependentUpon>AppointmentForm.resx</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\CityFormLocal.es-es.resx">
        <DependentUpon>CityFormLocal.resx</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\MainWindow.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>MainWindow.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\CustomerFormLocal.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CustomerFormLocal.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\AddressFormLocal.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>AddressFormLocal.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\CityFormLocal.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CityFormLocal.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\AppointmentForm.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>AppointmentForm.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\MainWindow.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>MainWindow.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
      <PackageReference Include="MySqlConnector" Version="2.6.2" />
    </ItemGroup>

</Project>
