<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>WGU_C969_Software_II_CS</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\CustomerFormLocal.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>CustomerForm.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\AddressFormLocal.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>AddressForm.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\CustomerFormLocal.es-es.resx">
        <DependentUpon>CustomerFormLocal.resx</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\AddressFormLocal.es-es.resx">
        <DependentUpon>AddressFormLocal.resx</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\CustomerFormLocal.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CustomerFormLocal.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\AddressFormLocal.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>AddressFormLocal.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
